
!               Copyright 1993 Colorado State University
!                       All Rights Reserved


      common/wth/prcurr,prcnxt,tmn2m,tmx2m, maxt,                        &
     &           precscalar, tminscalar,tmaxscalar,wthinput, wthstart

      integer wthinput, wthstart

      real prcurr(12), prcnxt(12), tmn2m(12), tmx2m(12), maxt
      real precscalar(12), tminscalar(12), tmaxscalar(12)

      save /wth/
